### ISSUE TITLE
New Mediator instances will always be added, even if another one is already existing

### ISSUE THREAD

**Issue by jayallanjethwa** [strangeioc/strangeioc#142] opened 2015-03-26 10:46 UTC
Hi!

Strange does not perform any checks to make sure that multiple Mediators of the same type cannot be added to the same view. If a Mediator is already attached to the GameObject upon binding, the existing Mediator should be used instead.

I have changed the component creation in MediationBinder.mapView in my working copy as following:
```C#
MonoBehaviour mediator = mono.gameObject.GetComponent(mediatorType) as MonoBehaviour ??
    mono.gameObject.AddComponent(mediatorType) as MonoBehaviour;
```
https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/mediation/impl/MediationBinder.cs#L130

**Comment by fogAndWhisky** [comment] 2015-03-26 15:41
I'll need to give this a little careful thought. You're probably correct. In general, I don't check because multiple mediators on a View are a perfectly valid pattern...preferable even in many cases. But more than one of the same does seem wrong I'd agree. 

The two main concerns which occur to me:

1. is there •never•  a valid case for two of the same Component on a GameObject?
2. Since Mediators are instantiated automatically based on bindings, what's the fail case we're addressing? I.e., what does a developer have to do to cause this to happen? Is it a real-world scenario?

Thanks!

**Comment by JayJayZZ** [comment] 2015-03-27 08:37
Regarding your main concerns:

1. While having multiple different mediators for a view are perfectly fine, IMHO the framework has to make sure you cannot have multiple active instances of the same. As far as I remember, Robotlegs also does not allow this scenario.

2. This issue came up for us since our current project utilizes a custom UI styling system which runs in the Unity Editor with [ExecuteInEditMode]. This causes the Mediators of the respective views to never be destroyed but instead stack on top of each other. In one case, we ended up with a party of up to 40 mediators, happily throwing null-reference exceptions all over the place until we noticed the actual problem.

**Comment by fogAndWhisky** [comment] 2015-03-27 15:17
Ok. Will definitely discuss with Will about this. It kind of feels like the issue is with the other piece of software...but whatever. Since you experience this as a real-world issue, and since you're probably correct that in at least most cases there should be only a single mediator, we'll look into it.

**Comment by JayJayZZ** [comment] 2015-03-27 15:20
"The other piece of software" would be the Unity Editor in this case. :-)
Thanks for considering it!

**Comment by fogAndWhisky** [comment] 2015-03-27 15:32
You said there was another plugin you were using. Sounds as if it's triggering creates without matching destroys. 

Unity allows multiples of the same component (e.g., 2 hinges). That's correct. Now imagine that principle extended to Mediators. Unlike how Robotlegs uses Mediators, Strange allows you to create as much mediation as you like, breaking up the job into small single-responsibility elements, if you like. 

My gut reaction, pending discussion with Will, is to leave default behavior as it is, but add a 'Once' method to this binding, to address the corner case.

**Comment by JayJayZZ** [comment] 2015-03-27 15:47
Sorry if there was any confusion about this - this is not another plugin but simply the built-in [ExecuteInEditMode] functionality. Once this is commented out, everything will behave as expected. With this Property though, Unity keeps the Mediators even after Play mode is left. 

I'm still new to Unity (coming from Flash) but this behaviour is quite odd, since I expect Components that have been dynamically added to a GameObject during play mode should _always_ be removed afterwards, but this doesn't seem to be the case. If there is any other way to avoid this issue, I'll be glad to hear it.

**Comment by fogAndWhisky** [comment] 2015-03-27 16:08
Well it's all neither here nor there with regard to the issue. We'll look into it regardless. :)

I don't have a lot of experience with ExecuteInEditMode, but it's purpose seems to be to do exactly what it says on the tin: execute things in edit mode, i.e., allow changes that are intended to persist. Therefore, when things get added, I can imagine they aren't going to get cleaned up.

**Comment by WillzZz** [comment] 2015-03-30 04:16
Hmm, I've regularly run in to problems like this using ExecuteInEditMode. I'm not surprised Strange has the same problem. There's no logic for cleanup or state management. Everything is additive. I think I found a hackweek project! 

In the meantime, it sounds like our plan should be to check if GetComponent<T> (where T is the mediator we're trying to instantiate) returns something or not. Easy peasy. Will that solve this issue?

**Comment by fogAndWhisky** [comment] 2015-03-30 05:04
Sure, there's no issue at all about how to catch it...more a question of whether we want to change default behavior or add the option to opt-out. Or perhaps this is a MediationBinder toggle where we say, in essence, we're in a mode where we need to treat this differently?

Or possibly I'm overthinking this, and we just change the default behavior. :P

**Comment by WillzZz** [comment] 2015-03-30 18:11
We only really need to answer one question, right? Is the most common use case far and away the obvious default?  Let's just solve the problem. When someone comes along who needs multiple of the same mediator, we can solve their problem, but I don't understand the use case for that. It wouldn't really be a mediator. They probably just want a component anyways?

Sorry for stream of consciousness typing, but those are my thoughts. That and ExecuteInEditMode needing some love, but that's internal work and not really within the scope of this conversation.

**Comment by fogAndWhisky** [comment] 2015-04-01 05:30
OK. fix is on tip. Commit a8630a5f4144b6

**Comment by fogAndWhisky** [comment] 2015-10-18 16:07
Since fix is on tip (and this seems to be a much-duplicated issue) I'm closing this.

**Closed by fogAndWhisky** 2015-10-18 16:07 UTC

**Comment by Bunzaga** [comment] 2017-02-01 23:38
This is actually breaking my current implementation.  I have several Components on the same GameObject, which I want to have their own Mediator->View association.  Instead, I get one mediator, for several Views.

The View has an Action, which the Mediator += to.  The second View's Action remains null, since there is never a second Mediator to += to it in OnRegister.

I'll see if I can hack an un-fix for this, I just wanted to let you know of the case.  I could probably get all the children Components of type ViewType and just += to all their Actions...
