### ISSUE TITLE
Maybe a bug in CrossContext

### ISSUE THREAD

**Issue by chansey97** [strangeioc/strangeioc#140] opened 2015-03-26 08:35 UTC
https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/extensions/context/impl/CrossContext.cs#L168

The crossContextBridge property return a crossContextDispatcher ?

**Comment by fogAndWhisky** [comment] 2015-03-26 15:26
Hmm...it does look odd, doesn't it? I'll need to do some crawling to be sure...it's been ages since I last gave any thought to this bit of code. Even if correct, a comment might be in order.

**Comment by WillzZz** [comment] 2015-03-30 18:13
I followed this logic around a few months back to answer the same question on google groups. It's not a bug, but the naming could be improved. Closing.

**Closed by WillzZz** 2015-03-30 18:13 UTC
